using System;
using System.Linq;
using System.Collections.Generic;

namespace AdhdWarrior {
 public static class CurrentFeatureTests {
  static int count;
  static void Check(bool ok,string text){if(!ok)throw new Exception(text);count++;}
  static bool Rejects(Action action){try{action();return false;}catch{return true;}}
  public static int Run(){
   count=0;var monday=new DateTime(2026,9,14);var data=new SaveData();
   Check(data.Version==11&&!data.Reminders.StartWithWindows&&!data.Reminders.CloseToTray,"New saves keep startup and tray behavior opt-in");
   Check(data.DailyTemplates.Count==4&&data.AutoGenerateDaily,"New saves contain enabled iOS daily defaults");
   Check(DailyTemplatesEngine.EnsureToday(data,monday)&&data.Quests.Count==4,"Matching daily templates generate today's quests");
   Check(!DailyTemplatesEngine.EnsureToday(data,monday)&&data.Quests.Count==4,"Daily template generation is duplicate safe");
   var first=data.DailyTemplates[0];first.Title="Updated daily";first.XP=75;DailyTemplatesEngine.ApplyToday(data,monday);var generated=data.Quests.Single(q=>q.DailyTemplateId==first.Id);Check(generated.Title=="Updated daily"&&generated.XP==75,"Editing a template updates today's unfinished quest");
   first.Enabled=false;DailyTemplatesEngine.ApplyToday(data,monday);Check(!data.Quests.Any(q=>q.DailyTemplateId==first.Id),"Pausing a template removes today's unfinished quest");
   var weekday=new SaveData();weekday.DailyTemplates=new List<DailyTemplate>{new DailyTemplate {Title="Monday only",XP=10,Weekdays=new List<int>{2}}};Check(DailyTemplatesEngine.EnsureToday(weekday,monday)&&!DailyTemplatesEngine.EnsureToday(weekday,monday.AddDays(1)),"Weekday schedules use iOS Sunday-one numbering");
   var rewards=new SaveData();rewards.Journey.Completions=3;DailyTemplatesEngine.ProcessMilestones(rewards);Check(rewards.PendingRewards.Count==1&&rewards.ClaimedMilestones.SequenceEqual(new[]{3}),"Three completions queue the first consistency reward");
   DailyTemplatesEngine.ProcessMilestones(rewards);Check(rewards.PendingRewards.Count==1,"Consistency rewards cannot queue twice");
   rewards.Coins=10000;Check(Rejects(()=>Journey.BuyGear(rewards,rewards.PendingRewards[0].GearId)),"The shop cannot sell an item already reserved in Rewards");
   Check(Identity.Unlocked(data,Identity.Avatars[0])&&Identity.Name(data)=="Player","Standard identity is available on new saves");
   var standard=Identity.Avatars[0];var freshReveal=Identity.RevealedPanels(data,standard);Check(freshReveal.SetEquals(new[]{1}),"A new character reveals only the Standard hood and face panel");
   data.Journey.Gear.Add("standard_clothes_6");Check(Identity.RevealedPanels(data,standard).SetEquals(new[]{0,1}),"Owned gear reveals its matching character panel");
   data.Journey.Gear.AddRange(GearCatalog.All.Where(g=>g.Sheet=="standard_clothes"&&!data.Journey.Gear.Contains(g.Id)).Select(g=>g.Id));Check(Identity.RevealedPanels(data,standard).Count==9,"A complete Standard set reveals the full portrait");
   var themed=Identity.Avatars.Single(x=>x.Id=="standard");Check(!Identity.Unlocked(data,themed),"Equipment avatar begins locked");data.Journey.Gear.AddRange(GearCatalog.All.Where(g=>g.Sheet=="standard").Select(g=>g.Id));Check(Identity.Unlocked(data,themed),"A complete equipment set unlocks its avatar");
   data.AvatarSet="standard";data.DisplayName="Ranger";data.Reminders.StartWithWindows=true;data.Reminders.CloseToTray=true;var round=Storage.Decode(Storage.Encode(data));Check(round.DisplayName=="Ranger"&&round.AvatarSet=="standard","Character identity round trips");Check(round.Reminders.StartWithWindows&&round.Reminders.CloseToTray,"Startup and tray preferences round trip");
   string removedGear=GearCatalog.All.First(g=>g.Sheet=="standard"&&round.Journey.Gear.Contains(g.Id)).Id;round.Journey.Gear.RemoveAll(x=>x==removedGear);Check(Rejects(()=>Storage.Decode(Storage.Encode(round))),"A locked selected avatar is rejected");
   foreach(var avatar in Identity.Avatars)Check(System.IO.File.Exists(System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"assets",avatar.Asset+".png")),"Avatar artwork packaged: "+avatar.Title);
   var old=new SaveData {Version=8};old.Journey.Completions=14;var migrated=Storage.Decode(Storage.Encode(old));Check(migrated.Version==11&&!migrated.AutoGenerateDaily&&migrated.ClaimedMilestones.SequenceEqual(new[]{3,7,14}),"Format 8 migration avoids surprise quests and reward backfill");
   return count;
  }
 }
}
