import Foundation

struct AppSaveData: Codable {
    var quests: [Quest]
    var streakQuests: [StreakQuest]
    var coinBalance: Int
    var inventory: [String: Int]
    var eggLevels: [String: Int]
    var eggProgressByItem: [String: Int]
    var eggHatchesByItem: [String: Int]
    var pets: [PetCompanion]
    var selectedPetID: UUID?
    var selectedEggItemID: String?
    var equippedLootRaw: [String: String]
    var pendingRewards: [PendingReward]
    var xpEvents: [XPEvent]
    var habitCompletionCounts: [String: Int]
    var completionEventsCount: Int
    var streakRemindersEnabled: Bool
    var reminderHour: Int
    var avatarImageData: Data?
    var myDisplayName: String
    var firstOpenedAt: Date?
    var interactionCountsByDay: [String: [String: Int]]
    var redeemedGiftIDs: [String]
    var redeemedQuestOfferIDs: [String]
    var trustedGiftSenderKeys: [String: String]
    var trustedFriends: [TrustedFriend]
    var giftSigningPrivateKeyData: Data?
    var googleSheetsWebhookURL: String
    var dailyQuestTemplates: [DailyQuestTemplate]
    var autoGenerateDailyQuests: Bool
    var activeWeeklyBossID: String
    var weeklyBossCurrentHP: Int
    var weeklyBossMaxHP: Int
    var weeklyBossWeekKey: String
    var weeklyBossLastDamageDayKey: String
    var weeklyBossHistory: [WeeklyBossHistoryEntry]
    var questDueRemindersEnabled: Bool
    var questOverdueReminderMinutes: Int
    var backlogQuestIDs: [UUID]
    var maxActiveQuests: Int
    var selectedEnergyMode: EnergyMode
    var questContextByID: [UUID: String]
    var questSnoozeReasonCounts: [String: Int]
    var questFrictionByTitle: [String: Int]
    var claimedConsistencyMilestones: [Int]
    var storePurchasesToday: Int
    var storePurchaseDayKey: String?
    var bossStoreBonusDayKey: String?
    var bodyDoublePartnerName: String
    var bodyDoubleSessionEndAt: Date?
    var focusSprintEndAt: Date?
    var focusSprintQuestID: UUID?
    var focusBreakEndAt: Date?
    var shutdownTopThree: [String]
    var shutdownLastCompletedDayKey: String?
    var rescueModeActive: Bool
    var rescueModePreviousMaxActiveQuests: Int?
    var rescueModePreviousEnergyMode: EnergyMode?
    var preferredSpriteSheetGender: SpriteSheetGender
    var preferredArtworkStyle: ArtworkStyle
    var preferredAvatarAssetName: String?
    var importedCalendarEventIDs: [String]
    var ignoredCalendarImportTitles: [String]
    var calendarImportGoogleOnly: Bool
    var calendarAutoImportEnabled: Bool
    var calendarImportedQuestCategory: QuestCategory
    var lastMorningQuestReviewDayKey: String?
    var showQuestQuickStartControls: Bool
    var debugModeEnabled: Bool
    var didMigrateEggSystemV2: Bool

    init(
        quests: [Quest],
        streakQuests: [StreakQuest],
        coinBalance: Int,
        inventory: [String: Int],
        eggLevels: [String: Int],
        eggProgressByItem: [String: Int],
        eggHatchesByItem: [String: Int],
        pets: [PetCompanion],
        selectedPetID: UUID?,
        selectedEggItemID: String?,
        equippedLootRaw: [String: String],
        pendingRewards: [PendingReward],
        xpEvents: [XPEvent],
        habitCompletionCounts: [String: Int],
        completionEventsCount: Int,
        streakRemindersEnabled: Bool,
        reminderHour: Int,
        avatarImageData: Data?,
        myDisplayName: String,
        firstOpenedAt: Date?,
        interactionCountsByDay: [String: [String: Int]],
        redeemedGiftIDs: [String],
        redeemedQuestOfferIDs: [String],
        trustedGiftSenderKeys: [String: String],
        trustedFriends: [TrustedFriend],
        giftSigningPrivateKeyData: Data?,
        googleSheetsWebhookURL: String,
        dailyQuestTemplates: [DailyQuestTemplate],
        autoGenerateDailyQuests: Bool,
        activeWeeklyBossID: String,
        weeklyBossCurrentHP: Int,
        weeklyBossMaxHP: Int,
        weeklyBossWeekKey: String,
        weeklyBossLastDamageDayKey: String,
        weeklyBossHistory: [WeeklyBossHistoryEntry],
        questDueRemindersEnabled: Bool,
        questOverdueReminderMinutes: Int,
        backlogQuestIDs: [UUID],
        maxActiveQuests: Int,
        selectedEnergyMode: EnergyMode,
        questContextByID: [UUID: String],
        questSnoozeReasonCounts: [String: Int],
        questFrictionByTitle: [String: Int],
        claimedConsistencyMilestones: [Int],
        storePurchasesToday: Int,
        storePurchaseDayKey: String?,
        bossStoreBonusDayKey: String?,
        bodyDoublePartnerName: String,
        bodyDoubleSessionEndAt: Date?,
        focusSprintEndAt: Date?,
        focusSprintQuestID: UUID?,
        focusBreakEndAt: Date?,
        shutdownTopThree: [String],
        shutdownLastCompletedDayKey: String?,
        rescueModeActive: Bool,
        rescueModePreviousMaxActiveQuests: Int?,
        rescueModePreviousEnergyMode: EnergyMode?,
        preferredSpriteSheetGender: SpriteSheetGender,
        preferredArtworkStyle: ArtworkStyle,
        preferredAvatarAssetName: String?,
        importedCalendarEventIDs: [String],
        ignoredCalendarImportTitles: [String],
        calendarImportGoogleOnly: Bool,
        calendarAutoImportEnabled: Bool,
        calendarImportedQuestCategory: QuestCategory,
        lastMorningQuestReviewDayKey: String? = nil,
        showQuestQuickStartControls: Bool,
        debugModeEnabled: Bool,
        didMigrateEggSystemV2: Bool
    ) {
        self.quests = quests
        self.streakQuests = streakQuests
        self.coinBalance = coinBalance
        self.inventory = inventory
        self.eggLevels = eggLevels
        self.eggProgressByItem = eggProgressByItem
        self.eggHatchesByItem = eggHatchesByItem
        self.pets = pets
        self.selectedPetID = selectedPetID
        self.selectedEggItemID = selectedEggItemID
        self.equippedLootRaw = equippedLootRaw
        self.pendingRewards = pendingRewards
        self.xpEvents = xpEvents
        self.habitCompletionCounts = habitCompletionCounts
        self.completionEventsCount = completionEventsCount
        self.streakRemindersEnabled = streakRemindersEnabled
        self.reminderHour = reminderHour
        self.avatarImageData = avatarImageData
        self.myDisplayName = myDisplayName
        self.firstOpenedAt = firstOpenedAt
        self.interactionCountsByDay = interactionCountsByDay
        self.redeemedGiftIDs = redeemedGiftIDs
        self.redeemedQuestOfferIDs = redeemedQuestOfferIDs
        self.trustedGiftSenderKeys = trustedGiftSenderKeys
        self.trustedFriends = trustedFriends
        self.giftSigningPrivateKeyData = giftSigningPrivateKeyData
        self.googleSheetsWebhookURL = googleSheetsWebhookURL
        self.dailyQuestTemplates = dailyQuestTemplates
        self.autoGenerateDailyQuests = autoGenerateDailyQuests
        self.activeWeeklyBossID = activeWeeklyBossID
        self.weeklyBossCurrentHP = weeklyBossCurrentHP
        self.weeklyBossMaxHP = weeklyBossMaxHP
        self.weeklyBossWeekKey = weeklyBossWeekKey
        self.weeklyBossLastDamageDayKey = weeklyBossLastDamageDayKey
        self.weeklyBossHistory = weeklyBossHistory
        self.questDueRemindersEnabled = questDueRemindersEnabled
        self.questOverdueReminderMinutes = questOverdueReminderMinutes
        self.backlogQuestIDs = backlogQuestIDs
        self.maxActiveQuests = maxActiveQuests
        self.selectedEnergyMode = selectedEnergyMode
        self.questContextByID = questContextByID
        self.questSnoozeReasonCounts = questSnoozeReasonCounts
        self.questFrictionByTitle = questFrictionByTitle
        self.claimedConsistencyMilestones = claimedConsistencyMilestones
        self.storePurchasesToday = storePurchasesToday
        self.storePurchaseDayKey = storePurchaseDayKey
        self.bossStoreBonusDayKey = bossStoreBonusDayKey
        self.bodyDoublePartnerName = bodyDoublePartnerName
        self.bodyDoubleSessionEndAt = bodyDoubleSessionEndAt
        self.focusSprintEndAt = focusSprintEndAt
        self.focusSprintQuestID = focusSprintQuestID
        self.focusBreakEndAt = focusBreakEndAt
        self.shutdownTopThree = shutdownTopThree
        self.shutdownLastCompletedDayKey = shutdownLastCompletedDayKey
        self.rescueModeActive = rescueModeActive
        self.rescueModePreviousMaxActiveQuests = rescueModePreviousMaxActiveQuests
        self.rescueModePreviousEnergyMode = rescueModePreviousEnergyMode
        self.preferredSpriteSheetGender = preferredSpriteSheetGender
        self.preferredArtworkStyle = preferredArtworkStyle
        self.preferredAvatarAssetName = preferredAvatarAssetName
        self.importedCalendarEventIDs = importedCalendarEventIDs
        self.ignoredCalendarImportTitles = ignoredCalendarImportTitles
        self.calendarImportGoogleOnly = calendarImportGoogleOnly
        self.calendarAutoImportEnabled = calendarAutoImportEnabled
        self.calendarImportedQuestCategory = calendarImportedQuestCategory
        self.lastMorningQuestReviewDayKey = lastMorningQuestReviewDayKey
        self.showQuestQuickStartControls = showQuestQuickStartControls
        self.debugModeEnabled = debugModeEnabled
        self.didMigrateEggSystemV2 = didMigrateEggSystemV2
    }

    enum CodingKeys: String, CodingKey {
        case quests
        case streakQuests
        case coinBalance
        case inventory
        case eggLevels
        case eggProgressByItem
        case eggHatchesByItem
        case pets
        case selectedPetID
        case selectedEggItemID
        case equippedLootRaw
        case pendingRewards
        case xpEvents
        case habitCompletionCounts
        case completionEventsCount
        case streakRemindersEnabled
        case reminderHour
        case avatarImageData
        case myDisplayName
        case firstOpenedAt
        case interactionCountsByDay
        case redeemedGiftIDs
        case redeemedQuestOfferIDs
        case trustedGiftSenderKeys
        case trustedFriends
        case giftSigningPrivateKeyData
        case googleSheetsWebhookURL
        case dailyQuestTemplates
        case autoGenerateDailyQuests
        case activeWeeklyBossID
        case weeklyBossCurrentHP
        case weeklyBossMaxHP
        case weeklyBossWeekKey
        case weeklyBossLastDamageDayKey
        case weeklyBossHistory
        case questDueRemindersEnabled
        case questOverdueReminderMinutes
        case backlogQuestIDs
        case maxActiveQuests
        case selectedEnergyMode
        case questContextByID
        case questSnoozeReasonCounts
        case questFrictionByTitle
        case claimedConsistencyMilestones
        case storePurchasesToday
        case storePurchaseDayKey
        case bossStoreBonusDayKey
        case bodyDoublePartnerName
        case bodyDoubleSessionEndAt
        case focusSprintEndAt
        case focusSprintQuestID
        case focusBreakEndAt
        case shutdownTopThree
        case shutdownLastCompletedDayKey
        case rescueModeActive
        case rescueModePreviousMaxActiveQuests
        case rescueModePreviousEnergyMode
        case preferredSpriteSheetGender
        case preferredArtworkStyle
        case preferredAvatarAssetName
        case importedCalendarEventIDs
        case ignoredCalendarImportTitles
        case calendarImportGoogleOnly
        case calendarAutoImportEnabled
        case calendarImportedQuestCategory
        case lastMorningQuestReviewDayKey
        case showQuestQuickStartControls
        case debugModeEnabled
        case didMigrateEggSystemV2
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        quests = try c.decode([Quest].self, forKey: .quests)
        streakQuests = try c.decode([StreakQuest].self, forKey: .streakQuests)
        coinBalance = try c.decodeIfPresent(Int.self, forKey: .coinBalance) ?? 0
        inventory = try c.decode([String: Int].self, forKey: .inventory)
        eggLevels = try c.decode([String: Int].self, forKey: .eggLevels)
        eggProgressByItem = try c.decode([String: Int].self, forKey: .eggProgressByItem)
        eggHatchesByItem = try c.decode([String: Int].self, forKey: .eggHatchesByItem)
        pets = try c.decode([PetCompanion].self, forKey: .pets)
        selectedPetID = try c.decodeIfPresent(UUID.self, forKey: .selectedPetID)
        selectedEggItemID = try c.decodeIfPresent(String.self, forKey: .selectedEggItemID)
        equippedLootRaw = try c.decode([String: String].self, forKey: .equippedLootRaw)
        pendingRewards = try c.decode([PendingReward].self, forKey: .pendingRewards)
        xpEvents = try c.decode([XPEvent].self, forKey: .xpEvents)
        habitCompletionCounts = try c.decode([String: Int].self, forKey: .habitCompletionCounts)
        completionEventsCount = try c.decode(Int.self, forKey: .completionEventsCount)
        streakRemindersEnabled = try c.decodeIfPresent(Bool.self, forKey: .streakRemindersEnabled) ?? false
        reminderHour = try c.decodeIfPresent(Int.self, forKey: .reminderHour) ?? 19
        avatarImageData = try c.decodeIfPresent(Data.self, forKey: .avatarImageData)
        myDisplayName = try c.decodeIfPresent(String.self, forKey: .myDisplayName) ?? "Player"
        firstOpenedAt = try c.decodeIfPresent(Date.self, forKey: .firstOpenedAt)
        interactionCountsByDay = try c.decodeIfPresent([String: [String: Int]].self, forKey: .interactionCountsByDay) ?? [:]
        redeemedGiftIDs = try c.decodeIfPresent([String].self, forKey: .redeemedGiftIDs) ?? []
        redeemedQuestOfferIDs = try c.decodeIfPresent([String].self, forKey: .redeemedQuestOfferIDs) ?? []
        trustedGiftSenderKeys = try c.decodeIfPresent([String: String].self, forKey: .trustedGiftSenderKeys) ?? [:]
        trustedFriends = try c.decodeIfPresent([TrustedFriend].self, forKey: .trustedFriends) ?? []
        giftSigningPrivateKeyData = try c.decodeIfPresent(Data.self, forKey: .giftSigningPrivateKeyData)
        googleSheetsWebhookURL = try c.decodeIfPresent(String.self, forKey: .googleSheetsWebhookURL) ?? ""
        dailyQuestTemplates = try c.decodeIfPresent([DailyQuestTemplate].self, forKey: .dailyQuestTemplates) ?? DailyQuestTemplate.standardDefaults
        autoGenerateDailyQuests = try c.decodeIfPresent(Bool.self, forKey: .autoGenerateDailyQuests) ?? true
        activeWeeklyBossID = try c.decodeIfPresent(String.self, forKey: .activeWeeklyBossID) ?? WeeklyBossDefinition.placeholders.first?.id ?? "mire_colossus"
        weeklyBossCurrentHP = try c.decodeIfPresent(Int.self, forKey: .weeklyBossCurrentHP) ?? 0
        weeklyBossMaxHP = try c.decodeIfPresent(Int.self, forKey: .weeklyBossMaxHP) ?? 0
        weeklyBossWeekKey = try c.decodeIfPresent(String.self, forKey: .weeklyBossWeekKey) ?? ""
        weeklyBossLastDamageDayKey = try c.decodeIfPresent(String.self, forKey: .weeklyBossLastDamageDayKey) ?? ""
        weeklyBossHistory = try c.decodeIfPresent([WeeklyBossHistoryEntry].self, forKey: .weeklyBossHistory) ?? []
        questDueRemindersEnabled = try c.decodeIfPresent(Bool.self, forKey: .questDueRemindersEnabled) ?? false
        questOverdueReminderMinutes = try c.decodeIfPresent(Int.self, forKey: .questOverdueReminderMinutes) ?? 60
        backlogQuestIDs = try c.decodeIfPresent([UUID].self, forKey: .backlogQuestIDs) ?? []
        maxActiveQuests = try c.decodeIfPresent(Int.self, forKey: .maxActiveQuests) ?? 8
        selectedEnergyMode = try c.decodeIfPresent(EnergyMode.self, forKey: .selectedEnergyMode) ?? .all
        questContextByID = try c.decodeIfPresent([UUID: String].self, forKey: .questContextByID) ?? [:]
        questSnoozeReasonCounts = try c.decodeIfPresent([String: Int].self, forKey: .questSnoozeReasonCounts) ?? [:]
        questFrictionByTitle = try c.decodeIfPresent([String: Int].self, forKey: .questFrictionByTitle) ?? [:]
        claimedConsistencyMilestones = try c.decodeIfPresent([Int].self, forKey: .claimedConsistencyMilestones) ?? []
        storePurchasesToday = try c.decodeIfPresent(Int.self, forKey: .storePurchasesToday) ?? 0
        storePurchaseDayKey = try c.decodeIfPresent(String.self, forKey: .storePurchaseDayKey)
        bossStoreBonusDayKey = try c.decodeIfPresent(String.self, forKey: .bossStoreBonusDayKey)
        bodyDoublePartnerName = try c.decodeIfPresent(String.self, forKey: .bodyDoublePartnerName) ?? ""
        bodyDoubleSessionEndAt = try c.decodeIfPresent(Date.self, forKey: .bodyDoubleSessionEndAt)
        focusSprintEndAt = try c.decodeIfPresent(Date.self, forKey: .focusSprintEndAt)
        focusSprintQuestID = try c.decodeIfPresent(UUID.self, forKey: .focusSprintQuestID)
        focusBreakEndAt = try c.decodeIfPresent(Date.self, forKey: .focusBreakEndAt)
        shutdownTopThree = try c.decodeIfPresent([String].self, forKey: .shutdownTopThree) ?? ["", "", ""]
        shutdownLastCompletedDayKey = try c.decodeIfPresent(String.self, forKey: .shutdownLastCompletedDayKey)
        rescueModeActive = try c.decodeIfPresent(Bool.self, forKey: .rescueModeActive) ?? false
        rescueModePreviousMaxActiveQuests = try c.decodeIfPresent(Int.self, forKey: .rescueModePreviousMaxActiveQuests)
        rescueModePreviousEnergyMode = try c.decodeIfPresent(EnergyMode.self, forKey: .rescueModePreviousEnergyMode)
        preferredSpriteSheetGender = try c.decodeIfPresent(SpriteSheetGender.self, forKey: .preferredSpriteSheetGender) ?? .male
        preferredArtworkStyle = try c.decodeIfPresent(ArtworkStyle.self, forKey: .preferredArtworkStyle) ?? .adult
        preferredAvatarAssetName = try c.decodeIfPresent(String.self, forKey: .preferredAvatarAssetName)
        importedCalendarEventIDs = try c.decodeIfPresent([String].self, forKey: .importedCalendarEventIDs) ?? []
        ignoredCalendarImportTitles = try c.decodeIfPresent([String].self, forKey: .ignoredCalendarImportTitles) ?? []
        calendarImportGoogleOnly = try c.decodeIfPresent(Bool.self, forKey: .calendarImportGoogleOnly) ?? true
        calendarAutoImportEnabled = try c.decodeIfPresent(Bool.self, forKey: .calendarAutoImportEnabled) ?? false
        calendarImportedQuestCategory = try c.decodeIfPresent(QuestCategory.self, forKey: .calendarImportedQuestCategory) ?? .work
        lastMorningQuestReviewDayKey = try c.decodeIfPresent(String.self, forKey: .lastMorningQuestReviewDayKey)
        showQuestQuickStartControls = try c.decodeIfPresent(Bool.self, forKey: .showQuestQuickStartControls) ?? false
        debugModeEnabled = try c.decodeIfPresent(Bool.self, forKey: .debugModeEnabled) ?? false
        didMigrateEggSystemV2 = try c.decodeIfPresent(Bool.self, forKey: .didMigrateEggSystemV2) ?? false
    }
}
