using System;
using System.IO;
using System.Linq;
using System.Drawing;
using System.Windows.Forms;
using System.Collections.Generic;
using System.Threading;
using System.Runtime.InteropServices;

namespace AdhdWarrior {
 static class Program {
  [DllImport("user32.dll",SetLastError=true)]static extern IntPtr FindWindow(string className,string windowName);
  [DllImport("user32.dll")]static extern bool ShowWindow(IntPtr window,int command);
  [DllImport("user32.dll")]static extern bool SetForegroundWindow(IntPtr window);
  static bool RestoreExisting(){var window=FindWindow(null,"ADHD Warrior — Windows 0.24.2");if(window==IntPtr.Zero)return false;ShowWindow(window,9);SetForegroundWindow(window);return true;}
  [STAThread] static int Main(string[] args) {
   Application.EnableVisualStyles(); Application.SetCompatibleTextRenderingDefault(false);
   if(args.Contains("--self-test")) return Tests.Run();
   if(args.Contains("--render-test")) return MainWindow.RenderSmokeTest();
   bool first; using(var mutex=new Mutex(true,"Local\\AdhdWarriorWindows"+(args.Contains("--preview-test")?"Test":""),out first)) {
    if(!first) {if(!RestoreExisting())MessageBox.Show("ADHD Warrior is already running in the notification area.");return 0;}
    try {Application.Run(new MainWindow(args.Contains("--preview-test"),args.Contains("--background")));return 0;} catch(Exception ex) {CrashReporter.Show(ex);return 1;}
   }
  }
 }
 public partial class MainWindow : Form {
  const int WM_SETREDRAW=0x000B;
  [DllImport("user32.dll")]static extern IntPtr SendMessage(IntPtr window,int message,IntPtr wParam,IntPtr lParam);
  SaveData data; string path=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"AdhdWarrior","save.json");
  Label stats=new Label(), heading=new Label(), status=new Label(); TextBox capture=new TextBox(), search=new TextBox();ComboBox categoryFilter=new ComboBox(),sortOrder=new ComboBox();
  TableLayoutPanel body,contentArea;Control quickBar,questBar;Panel encounterRail;PictureBox railBossArt,railPetArt;Label railBossName,railBossHP,railPetName,railLoot;JourneyMeter railBossMeter;ToolTip tips=new ToolTip {AutoPopDelay=8000,InitialDelay=350,ReshowDelay=100};
  BufferedFlowLayoutPanel cards=new BufferedFlowLayoutPanel(); string view="Today"; HashSet<string> selected=new HashSet<string>();
  Color ink=Theme.Text, green=Theme.Emerald, paper=Theme.Canvas;bool testMode,startHidden;
  public MainWindow(bool testMode=false,bool startHidden=false) {
   this.testMode=testMode;this.startHidden=startHidden;
   SetStyle(ControlStyles.UserPaint|ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer|ControlStyles.ResizeRedraw,true);DoubleBuffered=true;UpdateStyles();
   if(testMode) path=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"test-state","save.json");
   data=Storage.Load(path);string loadNotice=Storage.LastLoadNotice;Journey.RefreshWeek(data,DateTime.Today);if(DailyTemplatesEngine.EnsureToday(data,DateTime.Today))Storage.Save(path,data); Text="ADHD Warrior — Windows 0.24.2"+(testMode?" [TEST DATA]":"");Icon=Icon.ExtractAssociatedIcon(Application.ExecutablePath); MinimumSize=new Size(1000,680); Size=new Size(1240,860); StartPosition=FormStartPosition.CenterScreen; Font=new Font("Segoe UI",10); BackColor=paper; ForeColor=ink; AutoScaleMode=AutoScaleMode.Dpi;
   var layout=new ForestLayout {BackgroundImage=Artwork("forest-twilight"),Dock=DockStyle.Fill,ColumnCount=2,RowCount=1}; layout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,220));layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100)); Controls.Add(layout);
   var nav=new FlowLayoutPanel {Dock=DockStyle.Fill,FlowDirection=FlowDirection.TopDown,WrapContents=false,AutoScroll=true,Padding=new Padding(18,28,12,12),BackColor=Theme.Sidebar,ForeColor=Theme.Text};layout.Controls.Add(nav,0,0);
   nav.Controls.Add(new Label {Text="ADHD\nWARRIOR",Font=new Font("Georgia",12,FontStyle.Bold),ForeColor=Theme.Gold,AutoSize=false,Size=new Size(150,76)});
   nav.Controls.Add(new Label {Text="Small steps. Real progress.",ForeColor=Theme.Muted,AutoSize=true,MaximumSize=new Size(165,0),Margin=new Padding(0,0,0,22)});
   foreach(string v in new[]{"Today","All quests","Review","Daily templates","Streak quests","Character","Familiars","Boss map","Equipment","Rewards","Completed","Archive","Settings"}) {string target=v;var b=Button(v,()=>{view=target;selected.Clear();Render();});b.AutoSize=false;b.Width=165;b.Height=36;b.TextAlign=ContentAlignment.MiddleLeft;b.Padding=new Padding(12,3,7,3);b.FlatAppearance.BorderSize=0;b.BackColor=Theme.Sidebar;b.Paint+=(sender,e)=>{if(view==target)using(var pen=new Pen(Theme.Gold,3))e.Graphics.DrawLine(pen,1,8,1,b.Height-8);};navigation.Add(v,b);nav.Controls.Add(b);}
   body=new TableLayoutPanel {BackColor=Color.Transparent,Dock=DockStyle.Fill,ColumnCount=1,RowCount=6,Padding=new Padding(30,24,30,14)};layout.Controls.Add(body,1,0);
   foreach(int h in new[]{58,88,52,52}) body.RowStyles.Add(new RowStyle(SizeType.Absolute,h)); body.RowStyles.Add(new RowStyle(SizeType.Percent,100));body.RowStyles.Add(new RowStyle(SizeType.Absolute,44));
   heading.Font=new Font("Georgia",25);heading.ForeColor=Theme.Text;heading.BackColor=Color.Transparent;heading.Dock=DockStyle.Fill;body.Controls.Add(heading,0,0);
   body.Controls.Add(BuildMetrics(),0,1);Theme.StyleInput(capture);Theme.StyleInput(search);
   var quick=new TableLayoutPanel {BackColor=Color.Transparent,Dock=DockStyle.Fill,ColumnCount=3};quick.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));quick.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,54));quick.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,54));
   capture.Dock=DockStyle.Fill;capture.MaxLength=500;capture.AccessibleName="Quick capture quest title";capture.KeyDown+=(s,e)=>{if(e.KeyCode==Keys.Enter){AddQuick();e.SuppressKeyPress=true;}};
   quick.Controls.Add(capture,0,0);quick.Controls.Add(IconButton("+","Capture quest",AddQuick,42),1,0);quick.Controls.Add(IconButton("✎","Open detailed quest editor",()=>Edit(null),42),2,0);quickBar=quick;body.Controls.Add(quick,0,2);
   var bar=new FlowLayoutPanel {BackColor=Color.Transparent,Dock=DockStyle.Fill,WrapContents=false};search.Width=120;search.AccessibleName="Search quests";search.TextChanged+=(s,e)=>Render();categoryFilter.DropDownStyle=ComboBoxStyle.DropDownList;categoryFilter.Width=180;categoryFilter.Items.AddRange(new object[]{"All categories","School","Work","Home","Life","Fun"});categoryFilter.SelectedIndex=0;categoryFilter.SelectedIndexChanged+=(s,e)=>Render();sortOrder.DropDownStyle=ComboBoxStyle.DropDownList;sortOrder.Width=148;sortOrder.Items.AddRange(new object[]{"Due date","XP high to low","Category","Title","Recently completed"});sortOrder.SelectedIndex=0;sortOrder.SelectedIndexChanged+=(s,e)=>Render();Theme.StyleInput(categoryFilter);Theme.StyleInput(sortOrder);bar.Controls.Add(new Label {Text="Search",AutoSize=true,Padding=new Padding(0,6,4,0)});bar.Controls.Add(search);bar.Controls.Add(categoryFilter);bar.Controls.Add(sortOrder);bar.Controls.Add(IconButton("✓","Complete selected quests",CompleteSelected));bar.Controls.Add(IconButton("↘","Archive selected quests",ArchiveSelected));questBar=bar;body.Controls.Add(bar,0,3);
   cards.BackColor=Color.Transparent;cards.Dock=DockStyle.Fill;cards.AutoScroll=true;cards.FlowDirection=FlowDirection.TopDown;cards.WrapContents=false;cards.SizeChanged+=(s,e)=>{if(!cards.WrapContents)ResizeCards();};contentArea=new TableLayoutPanel {Dock=DockStyle.Fill,ColumnCount=2,RowCount=1,BackColor=Color.Transparent,Margin=Padding.Empty};contentArea.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));contentArea.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,0));contentArea.Controls.Add(cards,0,0);encounterRail=BuildEncounterRail();contentArea.Controls.Add(encounterRail,1,0);body.Controls.Add(contentArea,0,4);body.SizeChanged+=(s,e)=>LayoutEncounterRail();
   status.BackColor=Color.Transparent;status.Dock=DockStyle.Fill;status.ForeColor=String.IsNullOrEmpty(loadNotice)?green:Theme.Gold;status.Text=String.IsNullOrEmpty(loadNotice)?"Capture a thought above. Enter adds it to today.":loadNotice;body.Controls.Add(status,0,5);Render();SetupReminders();
   FormClosed+=(s,e)=>{DisposeReminders();foreach(var item in artCache.Values)item.Dispose();};
  }
  Button Button(string title,Action action) {var b=new ThemedButton {Text=title,AutoSize=true,Height=34,FlatStyle=FlatStyle.Flat,BackColor=Theme.Raised,ForeColor=ink,Margin=new Padding(0,0,8,8),Padding=new Padding(7,3,7,3)};Theme.StyleButton(b,title=="Complete"||title=="+ Capture"||title=="Save quest");b.Click+=(s,e)=>action();return b;}
  Button CardButton(string title,int width,Action action){var b=Button(title,action);b.AutoSize=false;b.Size=new Size(width,34);b.Margin=new Padding(0,0,5,0);b.Padding=Padding.Empty;return b;}
  Button IconButton(string glyph,string description,Action action,int width=40){var b=CardButton(glyph,width,action);b.AccessibleName=description;b.Font=new Font("Segoe UI Symbol",9,FontStyle.Bold);tips.SetToolTip(b,description);return b;}
  Panel BuildEncounterRail(){var panel=new Panel {Dock=DockStyle.Fill,BackColor=Theme.Surface,Padding=new Padding(14),Margin=new Padding(12,0,0,0)};Theme.Frame(panel,Theme.Coral);var stack=new TableLayoutPanel {Dock=DockStyle.Fill,ColumnCount=1,RowCount=8};stack.RowStyles.Add(new RowStyle(SizeType.Absolute,28));stack.RowStyles.Add(new RowStyle(SizeType.Absolute,125));stack.RowStyles.Add(new RowStyle(SizeType.Absolute,42));stack.RowStyles.Add(new RowStyle(SizeType.Absolute,20));stack.RowStyles.Add(new RowStyle(SizeType.Absolute,26));stack.RowStyles.Add(new RowStyle(SizeType.Absolute,100));stack.RowStyles.Add(new RowStyle(SizeType.Absolute,34));stack.RowStyles.Add(new RowStyle(SizeType.Percent,100));stack.Controls.Add(new Label {Text="CURRENT ENCOUNTER",Dock=DockStyle.Fill,Font=new Font("Segoe UI",8,FontStyle.Bold),ForeColor=Theme.Coral,TextAlign=ContentAlignment.MiddleCenter},0,0);railBossArt=new PictureBox {Dock=DockStyle.Fill,SizeMode=PictureBoxSizeMode.Zoom,Padding=new Padding(4)};stack.Controls.Add(railBossArt,0,1);railBossName=new Label {Dock=DockStyle.Fill,Font=new Font("Georgia",12,FontStyle.Bold),ForeColor=Theme.Text,TextAlign=ContentAlignment.MiddleCenter};stack.Controls.Add(railBossName,0,2);railBossMeter=new JourneyMeter {Dock=DockStyle.Fill,Accent=Theme.Coral};stack.Controls.Add(railBossMeter,0,3);railBossHP=new Label {Dock=DockStyle.Fill,ForeColor=Theme.Muted,TextAlign=ContentAlignment.TopCenter,Font=new Font("Segoe UI",8)};stack.Controls.Add(railBossHP,0,4);railPetArt=new PictureBox {Dock=DockStyle.Fill,SizeMode=PictureBoxSizeMode.Zoom,Padding=new Padding(5)};stack.Controls.Add(railPetArt,0,5);railPetName=new Label {Dock=DockStyle.Fill,Font=new Font("Segoe UI",9,FontStyle.Bold),ForeColor=Theme.Violet,TextAlign=ContentAlignment.MiddleCenter};stack.Controls.Add(railPetName,0,6);railLoot=new Label {Dock=DockStyle.Fill,ForeColor=Theme.Muted,TextAlign=ContentAlignment.TopCenter,Font=new Font("Segoe UI",8)};stack.Controls.Add(railLoot,0,7);panel.Controls.Add(stack);return panel;}
  void LayoutEncounterRail(){if(contentArea==null)return;bool questGrid=view=="Today"||view=="All quests"||view=="Review"||view=="Completed"||view=="Archive";bool show=questGrid&&body.ClientSize.Width>=860;encounterRail.Visible=show;contentArea.ColumnStyles[1].Width=show?230:0;if(show)UpdateEncounterRail();}
  void UpdateEncounterRail(){var pet=Journey.ActivePet(data);int boss=data.Journey.BossIndex,stage=Journey.Stage(pet),loot=pet.EggStage==4?Math.Min(100,pet.LootSkill*stage):0;railBossArt.Image=Artwork(boss<9?"weekly_monsters_1_9":"weekly_monsters_10_18",boss%9);railBossArt.AccessibleName=Journey.Bosses[boss]+" boss";railBossName.Text=Journey.Bosses[boss];railBossMeter.Maximum=Math.Max(1,data.Journey.BossMaxHP);railBossMeter.Value=data.Journey.BossHP;railBossHP.Text=data.Journey.BossHP+" / "+data.Journey.BossMaxHP+" HP";railPetArt.Image=Artwork(Journey.Definition(pet).Art[stage]);railPetArt.AccessibleName=Journey.PetName(pet)+" familiar";railPetName.Text=Journey.PetName(pet);railLoot.Text=pet.EggStage<4?"Loot unlocks after hatching.":pet.LootSkill==0?"0% loot chance\nSpend a familiar skill point on Loot Chance.":loot+"% bonus loot chance";}
  bool Change(Action action,string message) {
   var before=Storage.Encode(data);
   try {action();Storage.Save(path,data);} catch(Exception ex) {data=Storage.Decode(before);Render();MessageBox.Show(this,"Your change was not saved. "+ex.Message,"Save problem",MessageBoxButtons.OK,MessageBoxIcon.Error);return false;}
   status.Text=message;Render();return true;
  }
  void AddQuick() {var title=capture.Text.Trim();if(title.Length==0){capture.Focus();return;}if(Change(()=>data.Quests.Add(new Quest {Title=title,Due=DateTime.Today.ToString("yyyy-MM-dd")}),"Captured. One small step is enough."))capture.Clear();capture.Focus();}
  void Edit(Quest q) {using(var editor=new QuestEditor(q)) if(editor.ShowDialog(this)==DialogResult.OK) {Change(()=>{if(q==null)data.Quests.Add(editor.Result);else {int index=data.Quests.IndexOf(q);data.Quests[index]=editor.Result;}},"Quest saved.");}}
  List<Quest> Selection() {return data.Quests.Where(q=>selected.Contains(q.Id)&&!q.Done&&!q.Archived).ToList();}
  void CompleteSelected() {var list=Selection();if(list.Count==0){status.Text="Select one or more active quests first.";return;}CompleteQuests(list);}
  void ArchiveSelected() {var list=Selection();if(list.Count==0){status.Text="Select active quests to archive. You can restore them later.";return;}Change(()=>{foreach(var q in list)q.Archived=true;},"Moved to Archive. Restore whenever you need.");selected.Clear();}
  void UndoLastCompletion(){if(data.LastCompletion==null){status.Text="There is no recent completion to undo.";return;}string title=data.LastCompletion.Title;if(MessageBox.Show(this,"Undo the most recent completion: "+title+"?\n\nXP, coins, boss damage, familiar progress, loot, streak progress, and generated repeats from that action will be restored.","Undo completion",MessageBoxButtons.YesNo,MessageBoxIcon.Question)!=DialogResult.Yes)return;Change(()=>data=CompletionUndo.Restore(data),"Completion undone. "+title+" is active again.");}
  void ResizeCards() {int full=Math.Max(300,cards.ClientSize.Width-60);foreach(Control c in cards.Controls){if(c.Tag as string=="quest-card"){c.Width=300;c.Height=420;continue;}c.Width=full;cards.SetFlowBreak(c,true);if(c is Label)c.Height=Math.Max(72,TextRenderer.MeasureText(c.Text,c.Font,new Size(c.Width-c.Padding.Horizontal,0),TextFormatFlags.WordBreak).Height+c.Padding.Vertical+8);foreach(Control child in c.Controls) if(child is CheckBox)child.Width=c.Width-32;}}
  void Note(string text) {cards.Controls.Add(new Label {Text=text,AutoSize=false,Height=100,Padding=new Padding(18),Font=new Font("Segoe UI",10),BackColor=Theme.Surface,ForeColor=Theme.Muted,Margin=new Padding(0,0,0,12)});}
  static void CheckButtonBounds(Control root,string page){foreach(Control child in root.Controls){var scroll=child.Parent as ScrollableControl;if(child is Button&&(scroll==null||!scroll.AutoScroll)&&(child.Left<0||child.Top<0||child.Right>child.Parent.ClientSize.Width+2||child.Bottom>child.Parent.ClientSize.Height+2))throw new InvalidOperationException(page+" clips the "+child.Text+" button at "+child.Bounds+" inside "+child.Parent.ClientSize+".");CheckButtonBounds(child,page);}}
  static void CheckTextFits(Control root,string page){foreach(Control child in root.Controls){var combo=child as ComboBox;if(combo!=null&&combo.Visible&&combo.SelectedItem!=null&&TextRenderer.MeasureText(combo.SelectedItem.ToString(),combo.Font).Width>combo.ClientSize.Width-28)throw new InvalidOperationException(page+" clips the ‘"+combo.SelectedItem+"’ filter.");var label=child as Label;if(label!=null&&label.Visible&&!label.AutoSize&&!label.AutoEllipsis&&label.ClientSize.Width>20&&label.ClientSize.Height>10&&!String.IsNullOrWhiteSpace(label.Text)){var needed=TextRenderer.MeasureText(label.Text,label.Font,new Size(Math.Max(1,label.ClientSize.Width-label.Padding.Horizontal),0),TextFormatFlags.WordBreak|TextFormatFlags.NoPadding);if(needed.Height>label.ClientSize.Height-label.Padding.Vertical+4)throw new InvalidOperationException(page+" clips the label ‘"+label.Text.Replace("\n"," / ")+"’.");}CheckTextFits(child,page);}}
  static IEnumerable<Control> Descendants(Control root){foreach(Control child in root.Controls){yield return child;foreach(var nested in Descendants(child))yield return nested;}}
  public static int RenderSmokeTest(){string report=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"render-test-results.txt");try{using(var window=new MainWindow(true)){window.ShowInTaskbar=false;window.StartPosition=FormStartPosition.Manual;window.Location=new Point(-20000,-20000);window.Show();foreach(var size in new[]{new Size(1000,680),new Size(1240,860),new Size(1600,1000)}){window.Size=size;foreach(var page in new[]{"Today","All quests","Review","Character","Familiars","Boss map","Equipment","Rewards","Completed","Archive","Settings"}){window.view=page;window.Render();bool grid=page=="Today"||page=="All quests"||page=="Review"||page=="Completed"||page=="Archive";if(window.cards.WrapContents!=grid||window.cards.FlowDirection!=(grid?FlowDirection.LeftToRight:FlowDirection.TopDown))throw new InvalidOperationException(page+" uses the wrong scrolling flow.");Application.DoEvents();if(grid){foreach(Control card in window.cards.Controls.Cast<Control>().Where(c=>c.Tag as string=="quest-card")){if(Descendants(card).OfType<PictureBox>().Any())throw new InvalidOperationException(page+" still embeds boss or familiar artwork inside a quest card.");if(Descendants(card).OfType<CategoryIcon>().Count()!=1)throw new InvalidOperationException(page+" quest card is missing its category icon.");}if(size.Width==1000&&window.encounterRail.Visible)throw new InvalidOperationException(page+" shows the encounter rail when it does not fit.");if(size.Width==1600&&!window.encounterRail.Visible)throw new InvalidOperationException(page+" does not show the encounter rail when room is available.");}CheckButtonBounds(window,page);CheckTextFits(window,page);using(var image=new Bitmap(window.ClientSize.Width,window.ClientSize.Height))window.DrawToBitmap(image,window.ClientRectangle);}}window.Close();}File.WriteAllText(report,"PASS: all primary pages rendered at 1000x680, 1240x860, and 1600x1000 with buffered repaint enabled; grid pages wrap, detail pages scroll vertically, and visible action buttons and filter text fit their containers; quest cards use category icons, and the encounter rail appears only when it fits.");return 0;}catch(Exception ex){File.WriteAllText(report,"FAIL: "+ex);return 1;}}
  void Render() {
   bool redraw=IsHandleCreated;if(redraw)SendMessage(Handle,WM_SETREDRAW,IntPtr.Zero,IntPtr.Zero);cards.SuspendLayout();try{foreach(Control c in cards.Controls.Cast<Control>().ToArray()){cards.Controls.Remove(c);c.Dispose();}
   bool questGrid=view=="Today"||view=="All quests"||view=="Review"||view=="Completed"||view=="Archive";cards.FlowDirection=questGrid?FlowDirection.LeftToRight:FlowDirection.TopDown;cards.WrapContents=questGrid;quickBar.Visible=questGrid;questBar.Visible=questGrid;body.RowStyles[2].Height=questGrid?52:0;body.RowStyles[3].Height=questGrid?52:0;LayoutEncounterRail();
   RefreshTheme();heading.Text=view; stats.Text="LEVEL "+Progression.Level(data.XP)+"     /     "+data.XP+" XP     /     "+data.Coins+" COINS     /     "+Game.Streak(data,DateTime.Today)+" DAY STREAK";
   if(view=="Streak quests")ShowStreaks();
   else if(view=="Daily templates")ShowDailyTemplates();
   else if(view=="Character")ShowCharacter();
   else if(view=="Familiars")ShowPets();
   else if(view=="Boss map")ShowBosses();
   else if(view=="Equipment")ShowGear();
   else if(view=="Rewards")ShowRewards();
   else if(view=="Settings") {
    Note("Windows preview 0.24.2\n\nYour progress is saved on this computer after every change. No account is required.");
    ShowCalendarSettings();ShowReminderSettings();cards.Controls.Add(Button("Export Windows backup…",Export));cards.Controls.Add(Button("Restore Windows backup…",Import));cards.Controls.Add(Button("Preview iOS import…",ImportIos));
    Note("Save location:\n"+path+"\n\nThe previous save is retained as save.json.bak.");Note("Backups use Windows format 13. Older Windows backups upgrade automatically. Encrypted calendar addresses stay on this Windows account and are excluded from backups.\n\nStill missing from Settings: appearance and text-size controls, sound and animation preferences, cloud sync, automatic updates, focus and body-double controls, and account or friend features.\n\nKeyboard: Enter to capture; Tab to move between controls; Space to select.");
   } else {
    if(view=="Today")ShowWelcome();
    string today=DateTime.Today.ToString("yyyy-MM-dd");
    IEnumerable<Quest> list=data.Quests;
    if(view=="Completed")list=list.Where(q=>q.Done&&!q.Archived);
    else if(view=="Archive")list=list.Where(q=>q.Archived);
    else {list=list.Where(q=>!q.Done&&!q.Archived);if(view=="Today")list=list.Where(q=>String.IsNullOrEmpty(q.Due)||String.CompareOrdinal(q.Due,today)<=0);if(view=="Review")list=list.Where(q=>!String.IsNullOrEmpty(q.Due)&&String.CompareOrdinal(q.Due,today)<0);}
    list=list.Where(q=>q.Title.IndexOf(search.Text,StringComparison.OrdinalIgnoreCase)>=0||q.Steps.Any(s=>s.Title.IndexOf(search.Text,StringComparison.OrdinalIgnoreCase)>=0));if(categoryFilter.SelectedIndex>0)list=list.Where(q=>q.Category==(string)categoryFilter.SelectedItem);string order=(string)sortOrder.SelectedItem;if(view=="Completed"&&order=="Due date")order="Recently completed";if(order=="XP high to low")list=list.OrderByDescending(q=>q.Done?q.AwardedXP:q.XP).ThenBy(q=>q.Due);else if(order=="Category")list=list.OrderBy(q=>q.Category).ThenBy(q=>q.Due);else if(order=="Title")list=list.OrderBy(q=>q.Title);else if(order=="Recently completed")list=list.OrderByDescending(q=>q.Completed).ThenBy(q=>q.Title);else list=list.OrderBy(q=>String.IsNullOrEmpty(q.Due)?"9999":q.Due).ThenBy(q=>q.DueTime).ThenBy(q=>q.Title);list=list.ToList();
    if(!list.Any())Note(view=="Review"?"Nothing overdue. You have room to breathe.":"No quests here yet. Capture a small next step above.");
    foreach(var q in list)AddCard(q,today);
   }
   ResizeCards();}finally{cards.ResumeLayout(true);if(redraw){SendMessage(Handle,WM_SETREDRAW,new IntPtr(1),IntPtr.Zero);Invalidate(true);Update();}}
  }
  void AddCard(Quest q,string today) {
   var pet=Journey.ActivePet(data);var petDefinition=Journey.Definition(pet);int stage=Journey.Stage(pet),lootChance=pet.EggStage==4?Math.Min(100,pet.LootSkill*stage):0,bonus=q.Done?Math.Max(0,q.AwardedXP-q.XP):Journey.Bonus(data,q,DateTime.Today),reward=q.Done?q.AwardedXP:q.XP+bonus,boss=q.Done&&!String.IsNullOrEmpty(q.CompletedBoss)?q.CompletedBossIndex:data.Journey.BossIndex;string bossName=q.Done&&!String.IsNullOrEmpty(q.CompletedBoss)?q.CompletedBoss:Journey.Bosses[boss];
   var panel=new PokerCardPanel {Tag="quest-card",ColumnCount=1,RowCount=6,Accent=Theme.Category(q.Category)};panel.RowStyles.Add(new RowStyle(SizeType.Absolute,112));panel.RowStyles.Add(new RowStyle(SizeType.Absolute,62));panel.RowStyles.Add(new RowStyle(SizeType.Absolute,44));panel.RowStyles.Add(new RowStyle(SizeType.Absolute,42));panel.RowStyles.Add(new RowStyle(SizeType.Percent,100));panel.RowStyles.Add(new RowStyle(SizeType.Absolute,48));
   var categoryHead=new TableLayoutPanel {Dock=DockStyle.Fill,ColumnCount=2,RowCount=1,BackColor=Color.FromArgb(35,45,59),Margin=new Padding(0,0,0,5)};categoryHead.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,92));categoryHead.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));var categoryIcon=new CategoryIcon {Category=q.Category,Accent=Theme.Category(q.Category),Dock=DockStyle.Fill,AccessibleName=q.Category+" quest icon"};categoryHead.Controls.Add(categoryIcon,0,0);categoryHead.Controls.Add(new Label {Text=q.Category.ToUpperInvariant()+"\nQUEST",Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleLeft,Font=new Font("Georgia",14,FontStyle.Bold),ForeColor=Theme.Category(q.Category)},1,0);panel.Controls.Add(categoryHead,0,0);
   var titleRow=new TableLayoutPanel {Dock=DockStyle.Fill,ColumnCount=2,RowCount=1,Margin=Padding.Empty};titleRow.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,28));titleRow.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));var check=new CheckBox {Text="",Checked=selected.Contains(q.Id),Dock=DockStyle.Fill,Enabled=!q.Done&&!q.Archived,AccessibleName="Select "+q.Title};var titleLabel=new Label {Text=q.Title,Dock=DockStyle.Fill,Font=new Font("Segoe UI",10,FontStyle.Bold),TextAlign=ContentAlignment.MiddleLeft};tips.SetToolTip(titleLabel,q.Title);check.CheckedChanged+=(s,e)=>{if(check.Checked)selected.Add(q.Id);else selected.Remove(q.Id);};titleLabel.Click+=(s,e)=>{if(check.Enabled)check.Checked=!check.Checked;};titleRow.Controls.Add(check,0,0);titleRow.Controls.Add(titleLabel,1,0);panel.Controls.Add(titleRow,0,1);
   bool overdue=!q.Done&&!String.IsNullOrEmpty(q.Due)&&String.CompareOrdinal(q.Due,today)<0;
   var rewards=new TableLayoutPanel {Dock=DockStyle.Fill,ColumnCount=3,RowCount=1,Margin=new Padding(0,2,0,3)};for(int i=0;i<3;i++)rewards.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,33.33f));string lootText=pet.EggStage<4?"LOCKED":pet.LootSkill==0?"TRAIN":lootChance+"% LOOT";string[] rewardText={reward+" XP",lootText,pet.EggStage<4?"+20 GROW":"+20 PET XP"};Color[] rewardColor={Theme.Blue,Theme.Gold,Theme.Violet};for(int i=0;i<3;i++)rewards.Controls.Add(new Label {Text=rewardText[i],Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleCenter,Font=new Font("Segoe UI",8,FontStyle.Bold),ForeColor=rewardColor[i],BackColor=Color.FromArgb(37,50,68),Margin=new Padding(i==0?0:3,0,0,0)},i,0);panel.Controls.Add(rewards,0,2);
   panel.Controls.Add(new Label {Text=q.Category+" · "+q.Rarity+"\n"+(String.IsNullOrEmpty(q.Due)?"Anytime":q.Due)+(overdue?" · OVERDUE":"")+(q.Repeat=="None"?"":" · "+q.Repeat),Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleLeft,AutoEllipsis=false,ForeColor=overdue?Theme.Coral:Theme.Category(q.Category),Font=new Font("Segoe UI",8)},0,3);
   var steps=new FlowLayoutPanel {Dock=DockStyle.Fill,FlowDirection=FlowDirection.TopDown,WrapContents=false,AutoScroll=true,Margin=new Padding(0)};if(q.Done){steps.Controls.Add(new Label {Text=(String.IsNullOrEmpty(q.CompletedBoss)?"Legacy completion":"Boss: "+q.CompletedBoss+" · "+q.BossDamage+" damage"+(q.BossDefeated?" · defeated":"")),AutoSize=true,ForeColor=Theme.Coral});steps.Controls.Add(new Label {Text=(String.IsNullOrEmpty(q.CompletedFamiliar)?"":"Familiar: "+q.CompletedFamiliar+" · +"+q.FamiliarXP+" XP"),AutoSize=true,ForeColor=Theme.Violet});if(q.LootAwarded.Count>0)steps.Controls.Add(new Label {Text="Loot: "+String.Join(", ",q.LootAwarded.Select(id=>{var gear=GearCatalog.All.FirstOrDefault(g=>g.Id==id);return gear==null?id:gear.Name;})),AutoSize=true,MaximumSize=new Size(235,0),ForeColor=Theme.Gold});}foreach(var step in q.Steps) {var item=step;int h=Math.Max(24,TextRenderer.MeasureText(item.Title,Font,new Size(225,0),TextFormatFlags.WordBreak).Height+4);var stepRow=new TableLayoutPanel {Width=250,Height=h,ColumnCount=2,RowCount=1,Margin=Padding.Empty};stepRow.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,27));stepRow.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));var cb=new CheckBox {Text="",Checked=item.Done,Dock=DockStyle.Fill,Enabled=!q.Done&&!q.Archived,AccessibleName="Small step: "+item.Title};var stepText=new Label {Text=item.Title,Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleLeft};tips.SetToolTip(stepText,item.Title);cb.CheckedChanged+=(s,e)=>Change(()=>item.Done=cb.Checked,"Small step saved.");stepText.Click+=(s,e)=>{if(cb.Enabled)cb.Checked=!cb.Checked;};stepRow.Controls.Add(cb,0,0);stepRow.Controls.Add(stepText,1,0);steps.Controls.Add(stepRow);}if(q.Steps.Count==0)steps.Controls.Add(new Label {Text="One clear objective",AutoSize=true,ForeColor=Theme.Muted,Padding=new Padding(3,6,0,0)});panel.Controls.Add(steps,0,4);
   var actions=new FlowLayoutPanel {Dock=DockStyle.Fill,WrapContents=false,Margin=new Padding(0),Padding=new Padding(0,5,0,0)};
   if(q.Archived) actions.Controls.Add(IconButton("↩","Restore quest",()=>Change(()=>q.Archived=false,"Quest restored.")));
   else if(!q.Done) {actions.Controls.Add(IconButton("✓","Complete quest",()=>CompleteQuests(new[]{q})));actions.Controls.Add(IconButton("✎","Edit quest",()=>Edit(q)));if(overdue)actions.Controls.Add(IconButton("↪","Move quest to today",()=>Change(()=>q.Due=today,"A fresh start. Quest moved to today.")));}
   else {var summary="Completed "+q.Completed+" · "+q.AwardedXP+" XP · "+q.CoinsAwarded+" coins"+(String.IsNullOrEmpty(q.CompletedBoss)?"":" · "+q.BossDamage+" damage to "+q.CompletedBoss);var history=new Label {Text=summary,AutoSize=false,Size=new Size(235,38),AutoEllipsis=true};tips.SetToolTip(history,summary);actions.Controls.Add(history);if(data.LastCompletion!=null&&data.LastCompletion.Kind=="Quest"&&data.LastCompletion.TargetIds.Contains(q.Id))actions.Controls.Add(IconButton("↶","Undo this completion",UndoLastCompletion));}
   panel.Controls.Add(actions,0,5);cards.Controls.Add(panel);
  }
  void Export() {using(var dialog=new SaveFileDialog {Filter="JSON backup|*.json",FileName="adhd-warrior-"+DateTime.Today.ToString("yyyy-MM-dd")+".json"}) if(dialog.ShowDialog(this)==DialogResult.OK) {try {File.WriteAllText(dialog.FileName,Storage.Encode(data));status.Text="Backup exported.";}catch(Exception ex){MessageBox.Show(this,ex.Message,"Export failed");}}}
  void Import() {using(var dialog=new OpenFileDialog {Filter="JSON backup|*.json"}) if(dialog.ShowDialog(this)==DialogResult.OK) {try {var incoming=Storage.Decode(File.ReadAllText(dialog.FileName));if(MessageBox.Show(this,"Restore "+incoming.Quests.Count+" quests from this Windows backup? Your current progress will be retained in a recovery backup.","Restore backup",MessageBoxButtons.OKCancel)!=DialogResult.OK)return;Storage.Save(path+".before-restore-"+DateTime.Now.ToString("yyyyMMdd-HHmmssfff")+".json",data);Change(()=>{data=incoming;Journey.RefreshWeek(data,DateTime.Today);},"Backup restored.");}catch(Exception ex){MessageBox.Show(this,ex.Message,"Could not restore backup");}}}
 }
 public class QuestEditor : Form {
  public Quest Result; TextBox title=new TextBox(),steps=new TextBox(); ComboBox category=new ComboBox(),repeat=new ComboBox(),rarity=new ComboBox();DateTimePicker due=new DateTimePicker(),time=new DateTimePicker();NumericUpDown xp=new NumericUpDown();Quest original;
  public QuestEditor(Quest q) {
   original=q;Text=q==null?"New quest":"Edit quest";Size=new Size(580,690);MinimumSize=Size;StartPosition=FormStartPosition.CenterParent;Font=new Font("Segoe UI",10);BackColor=Theme.Canvas;ForeColor=Theme.Text;
   var form=new TableLayoutPanel {Dock=DockStyle.Fill,ColumnCount=2,RowCount=9,Padding=new Padding(22)};form.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,100));form.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));Controls.Add(form);
   title.MaxLength=500;rarity.Items.AddRange(Progression.Rarities);rarity.DropDownStyle=ComboBoxStyle.DropDownList;category.Items.AddRange(new object[]{"School","Work","Home","Life","Fun"});repeat.Items.AddRange(new object[]{"None","Daily","Weekly"});category.DropDownStyle=repeat.DropDownStyle=ComboBoxStyle.DropDownList;
   due.Format=DateTimePickerFormat.Short;due.ShowCheckBox=true;due.Checked=false;time.Format=DateTimePickerFormat.Custom;time.CustomFormat="h:mm tt";time.ShowCheckBox=true;time.Checked=false;time.Enabled=false;due.ValueChanged+=(s,e)=>time.Enabled=due.Checked;xp.Minimum=5;xp.Maximum=1000;xp.Increment=5;xp.Value=50;steps.Multiline=true;steps.ScrollBars=ScrollBars.Vertical;
   string[] labels={"Quest","Category","Due date","Due time","Repeat","Rarity","XP reward","Steps\n(one per line)"};Control[] inputs={title,category,due,time,repeat,rarity,xp,steps};
   for(int i=0;i<inputs.Length;i++){form.RowStyles.Add(new RowStyle(i==7?SizeType.Percent:SizeType.Absolute,i==7?100:48));form.Controls.Add(new Label {Text=labels[i],AutoSize=true},0,i);Theme.StyleInput(inputs[i]);inputs[i].Dock=DockStyle.Fill;form.Controls.Add(inputs[i],1,i);}
   rarity.SelectedItem=q==null?"Common":q.Rarity;rarity.SelectedIndexChanged+=(s,e)=>{if(rarity.SelectedItem!=null)xp.Value=Progression.QuestXP((string)rarity.SelectedItem);};
   category.SelectedItem=q==null?"Life":q.Category;repeat.SelectedItem=q==null?"None":q.Repeat;
   if(q!=null) {title.Text=q.Title;xp.Value=q.XP;steps.Text=String.Join(Environment.NewLine,q.Steps.Select(s=>s.Title));DateTime d;if(DateTime.TryParse(q.Due,out d)){due.Value=d;due.Checked=true;time.Enabled=true;}if(DateTime.TryParseExact(q.DueTime,"HH:mm",System.Globalization.CultureInfo.InvariantCulture,System.Globalization.DateTimeStyles.None,out d)){time.Value=d;time.Checked=true;}}
   var buttons=new FlowLayoutPanel {Dock=DockStyle.Fill,AutoSize=true};var save=new ThemedButton {Text="Save quest",AutoSize=true};var cancel=new ThemedButton {Text="Cancel",DialogResult=DialogResult.Cancel,AutoSize=true};Theme.StyleButton(save,true);Theme.StyleButton(cancel);buttons.Controls.Add(save);buttons.Controls.Add(cancel);form.Controls.Add(buttons,1,8);form.RowStyles.Add(new RowStyle(SizeType.Absolute,44));AcceptButton=save;CancelButton=cancel;
   save.Click+=(s,e)=>{
    var lines=steps.Lines.Select(x=>x.Trim()).Where(x=>x.Length>0).ToList();
    if(String.IsNullOrWhiteSpace(title.Text)||lines.Count>100||lines.Any(x=>x.Length>500)){MessageBox.Show(this,"Add a quest title and up to 100 steps of 500 characters each.");return;}
    Result=new Quest {Id=original==null?Guid.NewGuid().ToString():original.Id,Title=title.Text.Trim(),Category=(string)category.SelectedItem,Rarity=(string)rarity.SelectedItem,Repeat=(string)repeat.SelectedItem,Due=due.Checked?due.Value.ToString("yyyy-MM-dd"):"",DueTime=due.Checked&&time.Checked?time.Value.ToString("HH:mm"):"",XP=(int)xp.Value,Steps=lines.Select((x,i)=>new Step {Title=x,Done=original!=null&&i<original.Steps.Count&&original.Steps[i].Title==x&&original.Steps[i].Done}).ToList()};DialogResult=DialogResult.OK;
   };
  }
 }
}
