using System;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Drawing;
using System.Diagnostics;
using System.Globalization;
using System.Security.Cryptography;
using System.Collections.Generic;
using System.Windows.Forms;

namespace AdhdWarrior {
 public class CalendarSyncSettings {public string Category {get;set;}public List<string> ImportedEventIds {get;set;}public string LastSync {get;set;}public string GoogleLastSync {get;set;}public string MicrosoftLastSync {get;set;}public bool AutoRefresh {get;set;}public int RefreshMinutes {get;set;}public CalendarSyncSettings(){Category="Work";ImportedEventIds=new List<string>();LastSync="";GoogleLastSync="";MicrosoftLastSync="";AutoRefresh=true;RefreshMinutes=30;}}
 public class CalendarImportEvent {public string Id,Title,Due,DueTime;public bool Cancelled;}
 public class CalendarSyncResult {public int Added,Updated,Cancelled;}
 public static class CalendarImport {
  static readonly byte[] Entropy=Encoding.UTF8.GetBytes("ADHD Warrior Google Calendar link");
  static string LinkPath(string provider){return Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"AdhdWarrior",provider+"-calendar-link.dat");}
  public static bool Linked(string provider){return File.Exists(LinkPath(provider));}
  public static bool IsSupportedLink(string provider,string value){Uri uri;return TryLink(provider,value,out uri);}
  static bool TryLink(string provider,string value,out Uri uri){if(!Uri.TryCreate((value??"").Trim(),UriKind.Absolute,out uri)||uri.Scheme!="https")return false;string host=uri.Host.ToLowerInvariant(),path=uri.AbsolutePath.ToLowerInvariant();if(provider=="google")return (host=="calendar.google.com"||host=="www.google.com")&&path.Contains("/calendar/ical/");if(provider=="microsoft")return (host=="outlook.office365.com"||host=="outlook.office.com"||host=="outlook.live.com")&&(path.EndsWith(".ics")||path.Contains("/owa/calendar/"));return false;}
  static Uri ValidateLink(string provider,string value){Uri uri;if(!TryLink(provider,value,out uri))throw new InvalidOperationException(provider=="microsoft"?"Paste the ICS link from Outlook on the web under Settings, Calendar, Shared calendars, Publish a calendar.":"Paste the Secret address in iCal format from Google Calendar settings.");return uri;}
  public static void SaveLink(string provider,string value){var uri=ValidateLink(provider,value);Directory.CreateDirectory(Path.GetDirectoryName(LinkPath(provider)));File.WriteAllBytes(LinkPath(provider),ProtectedData.Protect(Encoding.UTF8.GetBytes(uri.AbsoluteUri),Entropy,DataProtectionScope.CurrentUser));}
  public static string LoadLink(string provider){if(!Linked(provider))return "";return Encoding.UTF8.GetString(ProtectedData.Unprotect(File.ReadAllBytes(LinkPath(provider)),Entropy,DataProtectionScope.CurrentUser));}
  public static void Disconnect(string provider){if(Linked(provider))File.Delete(LinkPath(provider));}
  public static void Validate(CalendarSyncSettings settings){if(settings==null||settings.ImportedEventIds==null||settings.ImportedEventIds.Count>10000||settings.ImportedEventIds.Distinct().Count()!=settings.ImportedEventIds.Count||settings.ImportedEventIds.Any(x=>String.IsNullOrWhiteSpace(x)||x.Length>1000)||!new[]{"School","Work","Home","Life","Fun"}.Contains(settings.Category))throw new InvalidDataException("Invalid calendar settings.");if(settings.RefreshMinutes==0)settings.RefreshMinutes=30;if(settings.RefreshMinutes<5||settings.RefreshMinutes>1440)throw new InvalidDataException("Invalid calendar refresh interval.");DateTime parsed;foreach(var value in new[]{settings.LastSync,settings.GoogleLastSync??"",settings.MicrosoftLastSync??""})if(value==null||value!=""&&!DateTime.TryParseExact(value,"yyyy-MM-dd HH:mm",CultureInfo.InvariantCulture,DateTimeStyles.None,out parsed))throw new InvalidDataException("Invalid calendar sync history.");settings.GoogleLastSync=settings.GoogleLastSync??"";settings.MicrosoftLastSync=settings.MicrosoftLastSync??"";}
  public static List<CalendarImportEvent> Parse(string text){var unfolded=(text??"").Replace("\r\n ","").Replace("\r\n\t","").Replace("\n ","").Replace("\n\t","");var result=new List<CalendarImportEvent>();foreach(var block in unfolded.Split(new[]{"BEGIN:VEVENT"},StringSplitOptions.None).Skip(1)){var end=block.IndexOf("END:VEVENT",StringComparison.Ordinal);if(end<0)continue;var lines=block.Substring(0,end).Replace("\r","").Split('\n');string uid=Value(lines,"UID"),title=Unescape(Value(lines,"SUMMARY")),start=Value(lines,"DTSTART"),recurrence=Value(lines,"RECURRENCE-ID");DateTime when;if(String.IsNullOrWhiteSpace(uid)||String.IsNullOrWhiteSpace(title)||!ParseDate(start,out when))continue;result.Add(new CalendarImportEvent {Id=String.IsNullOrWhiteSpace(recurrence)?uid:uid+"|"+recurrence,Title=title,Due=when.ToString("yyyy-MM-dd"),DueTime=start.Length>8?when.ToString("HH:mm"):"",Cancelled=Value(lines,"STATUS").Equals("CANCELLED",StringComparison.OrdinalIgnoreCase)});}return result;}
  static string Value(string[] lines,string key){var line=lines.FirstOrDefault(x=>x.StartsWith(key+":",StringComparison.OrdinalIgnoreCase)||x.StartsWith(key+";",StringComparison.OrdinalIgnoreCase));if(line==null)return "";int colon=line.IndexOf(':');return colon<0?"":line.Substring(colon+1).Trim();}
  static string Unescape(string text){return text.Replace("\\n"," ").Replace("\\N"," ").Replace("\\,",",").Replace("\\;",";").Replace("\\\\","\\").Trim();}
  static bool ParseDate(string value,out DateTime result){result=DateTime.MinValue;if(String.IsNullOrEmpty(value))return false;string clean=value.EndsWith("Z")?value.Substring(0,value.Length-1):value;string[] formats={"yyyyMMdd","yyyyMMdd'T'HHmmss","yyyyMMdd'T'HHmm"};if(!DateTime.TryParseExact(clean,formats,CultureInfo.InvariantCulture,DateTimeStyles.None,out result))return false;if(value.EndsWith("Z"))result=DateTime.SpecifyKind(result,DateTimeKind.Utc).ToLocalTime();return true;}
  public static List<CalendarImportEvent> Download(string provider){try{using(var client=new WebClient()){client.Headers[HttpRequestHeader.UserAgent]="ADHD Warrior Windows";return Parse(client.DownloadString(ValidateLink(provider,LoadLink(provider))));}}catch(WebException ex){var response=ex.Response as HttpWebResponse;if(provider=="google"&&response!=null&&response.StatusCode==HttpStatusCode.NotFound)throw new InvalidOperationException("Google returned 404 for this calendar. A Public address only works when the calendar is public. In Google Calendar, open Settings and sharing for this calendar, choose Integrate calendar, and copy the Secret address in iCal format instead. Keep that secret address private.");throw;}}
  public static CalendarSyncResult Reconcile(SaveData data,string provider,IEnumerable<CalendarImportEvent> incoming,string category,DateTime now){var result=new CalendarSyncResult();string prefix=provider+":";var events=incoming.Take(500).ToList();var seen=new HashSet<string>();foreach(var item in events){string key=prefix+item.Id;seen.Add(key);var quest=data.Quests.FirstOrDefault(q=>q.CalendarEventId==key||provider=="google"&&q.CalendarEventId==item.Id);if(item.Cancelled){if(quest!=null&&!quest.Done&&!quest.Archived){quest.Archived=true;result.Cancelled++;}continue;}if(quest==null){quest=new Quest {CalendarEventId=key};data.Quests.Add(quest);result.Added++;}else if(quest.Done||quest.Archived)continue;if(quest.Title!=item.Title||quest.Due!=item.Due||quest.DueTime!=item.DueTime||quest.Category!=category)result.Updated++;quest.Title=item.Title;quest.Due=item.Due;quest.DueTime=item.DueTime;quest.Category=category;if(!data.CalendarSync.ImportedEventIds.Contains(key))data.CalendarSync.ImportedEventIds.Add(key);}string today=now.Date.ToString("yyyy-MM-dd");foreach(var quest in data.Quests.Where(q=>!q.Done&&!q.Archived&&q.CalendarEventId!=null&&(q.CalendarEventId.StartsWith(prefix)||provider=="google"&&!q.CalendarEventId.Contains(":"))&&String.CompareOrdinal(q.Due,today)>=0&&!seen.Contains(q.CalendarEventId)&&!(provider=="google"&&seen.Contains(prefix+q.CalendarEventId))).ToList()){quest.Archived=true;result.Cancelled++;}string stamp=now.ToString("yyyy-MM-dd HH:mm");data.CalendarSync.LastSync=stamp;if(provider=="google")data.CalendarSync.GoogleLastSync=stamp;else data.CalendarSync.MicrosoftLastSync=stamp;return result;}
 }
 public partial class MainWindow {
  bool calendarRefreshing;
  void CheckAutomaticCalendarRefresh(DateTime now){if(testMode||calendarRefreshing||!data.CalendarSync.AutoRefresh)return;DateTime last;if(DateTime.TryParseExact(data.CalendarSync.LastSync,"yyyy-MM-dd HH:mm",CultureInfo.InvariantCulture,DateTimeStyles.None,out last)&&now-last<TimeSpan.FromMinutes(data.CalendarSync.RefreshMinutes))return;var providers=new[]{"google","microsoft"}.Where(CalendarImport.Linked).ToList();if(providers.Count==0)return;calendarRefreshing=true;System.Threading.Tasks.Task.Run(()=>providers.Select(p=>new {Provider=p,Events=CalendarImport.Download(p).Where(x=>x.Cancelled||String.CompareOrdinal(x.Due,DateTime.Today.AddDays(-1).ToString("yyyy-MM-dd"))>=0).ToList()}).ToList()).ContinueWith(task=>{if(IsDisposed)return;BeginInvoke((Action)(()=>{calendarRefreshing=false;if(task.IsFaulted){status.Text="Automatic calendar refresh will retry later: "+task.Exception.GetBaseException().Message;return;}var totals=new CalendarSyncResult();if(Change(()=>{foreach(var feed in task.Result){var result=CalendarImport.Reconcile(data,feed.Provider,feed.Events,data.CalendarSync.Category,DateTime.Now);totals.Added+=result.Added;totals.Updated+=result.Updated;totals.Cancelled+=result.Cancelled;}},"Calendars refreshed automatically."))status.Text="Calendars refreshed: "+totals.Added+" added · "+totals.Updated+" updated · "+totals.Cancelled+" archived.";}));});}
  void ShowCalendarSettings(){Note("Linked calendars\nGoogle Calendar and Microsoft 365 events become quests. Refreshes update changed names and times; cancelled or removed future events move safely to Archive. Published addresses are encrypted for this Windows account and excluded from backups.");var auto=new CheckBox {Text="Refresh linked calendars automatically every 30 minutes",Checked=data.CalendarSync.AutoRefresh,AutoSize=true,ForeColor=Theme.Text};auto.CheckedChanged+=(s,e)=>Change(()=>data.CalendarSync.AutoRefresh=auto.Checked,"Calendar refresh preference saved.");cards.Controls.Add(auto);ShowCalendarProvider("google","Google Calendar","Secret iCal address","https://calendar.google.com/calendar/u/0/r/settings",Theme.Gold);ShowCalendarProvider("microsoft","Microsoft 365 Calendar","Published Outlook ICS link","https://outlook.office.com/calendar/options/calendar/SharedCalendars",Theme.Blue);}
  void ShowCalendarProvider(string provider,string title,string addressLabel,string helpUrl,Color accent){var settings=data.CalendarSync;bool linked=CalendarImport.Linked(provider);string last=provider=="google"?settings.GoogleLastSync:settings.MicrosoftLastSync;var panel=new FlowLayoutPanel {FlowDirection=FlowDirection.TopDown,WrapContents=false,AutoSize=false,Height=245,Padding=new Padding(18),BackColor=Theme.Surface,Margin=new Padding(0,0,0,12)};Theme.Frame(panel,accent);panel.Controls.Add(new Label {Text=title+" · "+(linked?"Linked":"Not linked")+(linked&&last!=""?" · Last sync "+last:""),AutoSize=true,Font=new Font("Segoe UI",11,FontStyle.Bold),ForeColor=linked?Theme.Emerald:accent});panel.Controls.Add(new Label {Text=addressLabel,AutoSize=true,ForeColor=Theme.Muted});var link=new TextBox {Width=520,UseSystemPasswordChar=true};Theme.StyleInput(link);panel.Controls.Add(link);var row=new FlowLayoutPanel {AutoSize=true};row.Controls.Add(new Label {Text="Imported quest category",AutoSize=true,Padding=new Padding(0,7,6,0)});var category=new ComboBox {DropDownStyle=ComboBoxStyle.DropDownList,Width=130};category.Items.AddRange(new object[]{"School","Work","Home","Life","Fun"});category.SelectedItem=settings.Category;Theme.StyleInput(category);row.Controls.Add(category);panel.Controls.Add(row);var actions=new FlowLayoutPanel {AutoSize=true,WrapContents=false};actions.Controls.Add(Button(linked?"Save link and sync now":"Link and import now",()=>SyncCalendarProvider(provider,link.Text,(string)category.SelectedItem)));actions.Controls.Add(Button("Open setup page",()=>{try{Process.Start(helpUrl);}catch(Exception ex){MessageBox.Show(this,ex.Message,"Could not open calendar settings");}}));if(linked)actions.Controls.Add(Button("Disconnect",()=>{CalendarImport.Disconnect(provider);status.Text=title+" disconnected. Imported quests were kept.";Render();}));panel.Controls.Add(actions);cards.Controls.Add(panel);}
  void SyncCalendarProvider(string provider,string link,string category){try{if(!String.IsNullOrWhiteSpace(link))CalendarImport.SaveLink(provider,link);if(!CalendarImport.Linked(provider))throw new InvalidOperationException("Paste the published calendar address first.");var events=CalendarImport.Download(provider).Where(x=>x.Cancelled||String.CompareOrdinal(x.Due,DateTime.Today.AddDays(-1).ToString("yyyy-MM-dd"))>=0).ToList();CalendarSyncResult result=null;if(Change(()=>{data.CalendarSync.Category=category;result=CalendarImport.Reconcile(data,provider,events,category,DateTime.Now);},"Calendar sync complete."))MessageBox.Show(this,result.Added+" added · "+result.Updated+" updated · "+result.Cancelled+" moved to Archive","Calendar sync");}catch(Exception ex){MessageBox.Show(this,"Calendar sync failed. "+ex.Message,"Calendar sync",MessageBoxButtons.OK,MessageBoxIcon.Error);}}
 }
}
