// Generated from iOS SharedGameModels.swift. Sprite tiles are converted from one-based to zero-based.
namespace AdhdWarrior { public static class GearCatalog { public static readonly GearDefinition[] All = {
new GearDefinition("library_1","Scholar Hood","UNCOMMON","HEAD","library",0),
new GearDefinition("library_2","Archivist Robe","RARE","CHEST","library",1),
new GearDefinition("library_3","Scriptbinder Gloves","UNCOMMON","HANDS","library",2),
new GearDefinition("library_4","Cataloguer Trousers","UNCOMMON","LEGS","library",3),
new GearDefinition("library_5","Archive Step Boots","RARE","FEET","library",4),
new GearDefinition("library_6","Quillstaff","EPIC","WEAPON","library",5),
new GearDefinition("library_7","Lampglass Pendant","RARE","OFFHAND","library",6),
new GearDefinition("library_8","Ring of Ink","UNCOMMON","ACCESSORY","library",7),
new GearDefinition("library_9","Ring of Memory","EPIC","RING","library",8),
new GearDefinition("standard_1","Arcanist Hood","UNCOMMON","HEAD","standard",0),
new GearDefinition("standard_2","Apprentice Robe","RARE","CHEST","standard",1),
new GearDefinition("standard_3","Spellweave Gloves","UNCOMMON","HANDS","standard",2),
new GearDefinition("standard_4","Runebound Leggings","UNCOMMON","LEGS","standard",3),
new GearDefinition("standard_5","Starstep Boots","RARE","FEET","standard",4),
new GearDefinition("standard_6","Focus Wand","EPIC","WEAPON","standard",5),
new GearDefinition("standard_7","Moon Sigil Charm","RARE","OFFHAND","standard",6),
new GearDefinition("standard_8","Ring of Sparks","UNCOMMON","ACCESSORY","standard",7),
new GearDefinition("standard_9","Ring of Echoes","EPIC","RING","standard",8),
new GearDefinition("standard_clothes_1","Traveler Hood","UNCOMMON","HEAD","standard_clothes",0),
new GearDefinition("standard_clothes_2","Wayfarer Tunic","RARE","CHEST","standard_clothes",1),
new GearDefinition("standard_clothes_3","Field Gloves","UNCOMMON","HANDS","standard_clothes",2),
new GearDefinition("standard_clothes_4","Roadworn Trousers","UNCOMMON","LEGS","standard_clothes",3),
new GearDefinition("standard_clothes_5","Everyday Boots","RARE","FEET","standard_clothes",4),
new GearDefinition("standard_clothes_6","Walking Staff","EPIC","WEAPON","standard_clothes",5),
new GearDefinition("standard_clothes_7","Keepsake Scarf","RARE","OFFHAND","standard_clothes",6),
new GearDefinition("standard_clothes_8","Simple Charm","UNCOMMON","ACCESSORY","standard_clothes",7),
new GearDefinition("standard_clothes_9","Plain Ring","EPIC","RING","standard_clothes",8),
new GearDefinition("garden_gnome_1","Garden Gnome Hat","UNCOMMON","HEAD","garden_gnome",0),
new GearDefinition("garden_gnome_2","Garden Gnome Vest","RARE","CHEST","garden_gnome",1),
new GearDefinition("garden_gnome_3","Garden Gnome Gloves","UNCOMMON","HANDS","garden_gnome",2),
new GearDefinition("garden_gnome_4","Garden Gnome Pants","UNCOMMON","LEGS","garden_gnome",3),
new GearDefinition("garden_gnome_5","Garden Gnome Boots","RARE","FEET","garden_gnome",4),
new GearDefinition("garden_gnome_6","Garden Gnome Shovel","EPIC","WEAPON","garden_gnome",5),
new GearDefinition("garden_gnome_7","Garden Gnome Pail","RARE","OFFHAND","garden_gnome",6),
new GearDefinition("garden_gnome_8","Garden Gnome Beard","UNCOMMON","ACCESSORY","garden_gnome",7),
new GearDefinition("garden_gnome_9","Garden Gnome Ring","EPIC","RING","garden_gnome",8),
new GearDefinition("wood_elf_1","Wood Elf Circlet","UNCOMMON","HEAD","wood_elf",0),
new GearDefinition("wood_elf_2","Wood Elf Cuirass","RARE","CHEST","wood_elf",1),
new GearDefinition("wood_elf_3","Wood Elf Gloves","UNCOMMON","HANDS","wood_elf",2),
new GearDefinition("wood_elf_4","Wood Elf Leafskirt","UNCOMMON","LEGS","wood_elf",3),
new GearDefinition("wood_elf_5","Wood Elf Boots","RARE","FEET","wood_elf",4),
new GearDefinition("wood_elf_6","Wood Elf Spear","EPIC","WEAPON","wood_elf",5),
new GearDefinition("wood_elf_7","Wood Elf Feather Charm","RARE","OFFHAND","wood_elf",6),
new GearDefinition("wood_elf_8","Wood Elf Braided Band","UNCOMMON","ACCESSORY","wood_elf",7),
new GearDefinition("wood_elf_9","Wood Elf Acorn Ring","EPIC","RING","wood_elf",8),
new GearDefinition("micah_1","Micah Dragon Helm","UNCOMMON","HEAD","micah",0),
new GearDefinition("micah_2","Micah Silk Headband","RARE","RING","micah",1),
new GearDefinition("micah_3","Micah Tassel Bracers","UNCOMMON","HANDS","micah",2),
new GearDefinition("micah_4","Micah Dragon Cuirass","RARE","CHEST","micah",3),
new GearDefinition("micah_5","Micah Lamellar Tassets","UNCOMMON","LEGS","micah",4),
new GearDefinition("micah_6","Micah Mountain Boots","RARE","FEET","micah",5),
new GearDefinition("micah_7","Micah Lantern","RARE","OFFHAND","micah",6),
new GearDefinition("micah_8","Micah Dragon Medallion","UNCOMMON","ACCESSORY","micah",7),
new GearDefinition("micah_9","Micah War Glaive","EPIC","WEAPON","micah",8),
new GearDefinition("stacy_1","Stacy Amethyst Tiara","UNCOMMON","HEAD","stacy",0),
new GearDefinition("stacy_2","Stacy Necklace","RARE","OFFHAND","stacy",1),
new GearDefinition("stacy_3","Stacy Earrings","UNCOMMON","HANDS","stacy",2),
new GearDefinition("stacy_4","Stacy Royal Gown","RARE","CHEST","stacy",3),
new GearDefinition("stacy_5","Stacy Overskirt","UNCOMMON","LEGS","stacy",4),
new GearDefinition("stacy_6","Stacy Jeweled Comb","UNCOMMON","RING","stacy",5),
new GearDefinition("stacy_7","Stacy Slippers","RARE","FEET","stacy",6),
new GearDefinition("stacy_8","Stacy Court Dagger","EPIC","WEAPON","stacy",7),
new GearDefinition("stacy_9","Stacy Gem Sash","EPIC","ACCESSORY","stacy",8),
new GearDefinition("emberforge_1","Emberforge Helm","UNCOMMON","HEAD","emberforge",0),
new GearDefinition("emberforge_2","Cinderplate Armor","RARE","CHEST","emberforge",1),
new GearDefinition("emberforge_3","Ashguard Gauntlets","UNCOMMON","HANDS","emberforge",2),
new GearDefinition("emberforge_4","Forgebound Greaves","UNCOMMON","LEGS","emberforge",3),
new GearDefinition("emberforge_5","Coalstep Boots","RARE","FEET","emberforge",4),
new GearDefinition("emberforge_6","Emberbrand Blade","EPIC","WEAPON","emberforge",5),
new GearDefinition("emberforge_7","Molten Sigil Amulet","RARE","OFFHAND","emberforge",6),
new GearDefinition("emberforge_8","Ring of Cinders","UNCOMMON","ACCESSORY","emberforge",7),
new GearDefinition("emberforge_9","Ring of Sparks","EPIC","RING","emberforge",8),
new GearDefinition("nightveil_1","Nightveil Hood","UNCOMMON","HEAD","nightveil",0),
new GearDefinition("nightveil_2","Veilbound Coat","RARE","CHEST","nightveil",1),
new GearDefinition("nightveil_3","Shadowtouch Gloves","UNCOMMON","HANDS","nightveil",2),
new GearDefinition("nightveil_4","Duskweave Leggings","UNCOMMON","LEGS","nightveil",3),
new GearDefinition("nightveil_5","Moonstep Boots","RARE","FEET","nightveil",4),
new GearDefinition("nightveil_6","Umbral Fang Blade","EPIC","WEAPON","nightveil",5),
new GearDefinition("nightveil_7","Pendant of Twilight","RARE","OFFHAND","nightveil",6),
new GearDefinition("nightveil_8","Ring of Quiet Stars","UNCOMMON","ACCESSORY","nightveil",7),
new GearDefinition("nightveil_9","Ring of Veiled Paths","EPIC","RING","nightveil",8),
};}}
